
import Classes.Case;
import Classes.Client;
import Classes.DataBase;
import javax.swing.ComboBoxModel;
import Classes.ResultSetComboBoxModel;
import com.mysql.jdbc.ResultSet;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class MainWindow extends javax.swing.JFrame {
    
    // CREATES DATABASE CONNECTION
    private DataBase DB = new DataBase();
    
    // CREATES NEW CASE & CLIENT
    private Case exercise_case = new Case();
    private Client case_client = new Client();


    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        
        // Set initial values
        this.cboxTelCodes.setSelectedIndex(3);
        this.rbtnPython.setSelected(true);
        this.rbtnHomework.setSelected(true);            
        this.rbtnHomework.addActionListener(radioListenerServices);
        this.rbtnTest.addActionListener(radioListenerServices);
        this.rbtnPython.addActionListener(radioListenerLanguages);
        this.rbtnHtmlCss.addActionListener(radioListenerLanguages);
        this.rbtnHtmlPhp.addActionListener(radioListenerLanguages);
        this.rbtnHtmlJavaScript.addActionListener(radioListenerLanguages);
        this.rbtnJava.addActionListener(radioListenerLanguages);
        this.exercise_case.setType(this.getSelectedRadioButtonIndexService()+1);
        this.exercise_case.setLanguage(this.getSelectedRadioButtonIndexLanguage()+1);
        this.exercise_case.setExercise_number((int) this.spnExercises.getValue());
        this.exercise_case.setDays((int) this.spnDeadline.getValue());
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Assets/Icono-TareaProgramada-3.png")));
        setDefaultCloseOperation(MainWindow.DO_NOTHING_ON_CLOSE);
        
        // Close Window Method
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int result = JOptionPane.showConfirmDialog(MainWindow.this, "Desea salir de la aplicación?", "Confirme", JOptionPane.YES_NO_OPTION);
                if (result == JOptionPane.YES_OPTION) {
                    // Perform your specific action before closing the window
                    DB.closeConnection();
                    setDefaultCloseOperation(MainWindow.EXIT_ON_CLOSE);
                    dispose();
                }
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        btnGrLanguages = new javax.swing.ButtonGroup();
        btnGrServiceType = new javax.swing.ButtonGroup();
        PanelTittle = new javax.swing.JPanel();
        lnlTareProgramada = new javax.swing.JLabel();
        PanelClientData = new javax.swing.JPanel();
        txtClientName = new javax.swing.JTextField();
        txtClientMail = new javax.swing.JTextField();
        txtClientTel = new javax.swing.JTextField();
        cboxTelCodes = new javax.swing.JComboBox<>();
        btnSaveClientInfo = new javax.swing.JButton();
        PanelCaseData = new javax.swing.JPanel();
        PanelProgammingLanguaje = new javax.swing.JPanel();
        lblProgrammingLanguaje = new javax.swing.JLabel();
        rbtnPython = new javax.swing.JRadioButton();
        rbtnHtmlCss = new javax.swing.JRadioButton();
        rbtnHtmlPhp = new javax.swing.JRadioButton();
        rbtnHtmlJavaScript = new javax.swing.JRadioButton();
        rbtnJava = new javax.swing.JRadioButton();
        PanelServiceType = new javax.swing.JPanel();
        lblServiceType = new javax.swing.JLabel();
        rbtnHomework = new javax.swing.JRadioButton();
        rbtnTest = new javax.swing.JRadioButton();
        PanelDeadline = new javax.swing.JPanel();
        lblDeadline = new javax.swing.JLabel();
        spnDeadline = new javax.swing.JSpinner();
        lblDays = new javax.swing.JLabel();
        PanelExerciseNumber = new javax.swing.JPanel();
        lblExerciseNumber = new javax.swing.JLabel();
        spnExercises = new javax.swing.JSpinner();
        btnExecuteCotization = new javax.swing.JButton();
        SeparatorBottom = new javax.swing.JSeparator();
        PanelCotization = new javax.swing.JPanel();
        lblCotizationPrice = new javax.swing.JLabel();
        btnAcceptCotization = new javax.swing.JButton();
        lblCotizationNote = new javax.swing.JLabel();
        PanelClientList = new javax.swing.JPanel();
        cboxClientList = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TAREA PROGRAMADA - COTIZACION");
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(680, 680));
        setResizable(false);

        PanelTittle.setBackground(new java.awt.Color(0, 0, 0));
        PanelTittle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lnlTareProgramada.setFont(new java.awt.Font("Town 10 Display Bold", 0, 24)); // NOI18N
        lnlTareProgramada.setForeground(new java.awt.Color(255, 255, 255));
        lnlTareProgramada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnlTareProgramada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Banner-TareaProgramada-2.png"))); // NOI18N
        lnlTareProgramada.setToolTipText("");

        javax.swing.GroupLayout PanelTittleLayout = new javax.swing.GroupLayout(PanelTittle);
        PanelTittle.setLayout(PanelTittleLayout);
        PanelTittleLayout.setHorizontalGroup(
            PanelTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lnlTareProgramada, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        PanelTittleLayout.setVerticalGroup(
            PanelTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTittleLayout.createSequentialGroup()
                .addComponent(lnlTareProgramada, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelClientData.setBackground(new java.awt.Color(0, 0, 0));
        PanelClientData.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black)), "Datos cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Town 10 Display Bold", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        txtClientName.setText("Nombre");
        txtClientName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtClientNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClientNameFocusLost(evt);
            }
        });

        txtClientMail.setText("Correo electrónico");
        txtClientMail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtClientMailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClientMailFocusLost(evt);
            }
        });

        txtClientTel.setText("Teléfono");
        txtClientTel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtClientTelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClientTelFocusLost(evt);
            }
        });

        cboxTelCodes.setModel(telCodesComboBoxModel());

        btnSaveClientInfo.setBackground(new java.awt.Color(182, 193, 255));
        btnSaveClientInfo.setFont(new java.awt.Font("Town 10 Display Bold", 0, 12)); // NOI18N
        btnSaveClientInfo.setText("Guardar");
        btnSaveClientInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveClientInfoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelClientDataLayout = new javax.swing.GroupLayout(PanelClientData);
        PanelClientData.setLayout(PanelClientDataLayout);
        PanelClientDataLayout.setHorizontalGroup(
            PanelClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelClientDataLayout.createSequentialGroup()
                        .addComponent(cboxTelCodes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClientTel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelClientDataLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClientMail, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelClientDataLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnSaveClientInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelClientDataLayout.setVerticalGroup(
            PanelClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClientMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelClientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClientTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxTelCodes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveClientInfo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelCaseData.setBackground(new java.awt.Color(0, 0, 0));
        PanelCaseData.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black), "Ficha del caso", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Town 10 Display Bold", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        lblProgrammingLanguaje.setFont(new java.awt.Font("Town 10 Display Bold", 0, 12)); // NOI18N
        lblProgrammingLanguaje.setText("Lenguaje de programación");

        btnGrLanguages.add(rbtnPython);
        rbtnPython.setText("Python");

        btnGrLanguages.add(rbtnHtmlCss);
        rbtnHtmlCss.setText("HTML-CSS");
        rbtnHtmlCss.setToolTipText("");

        btnGrLanguages.add(rbtnHtmlPhp);
        rbtnHtmlPhp.setText("HTML-PHP");

        btnGrLanguages.add(rbtnHtmlJavaScript);
        rbtnHtmlJavaScript.setText("HTML-JS");

        btnGrLanguages.add(rbtnJava);
        rbtnJava.setText("Java");

        javax.swing.GroupLayout PanelProgammingLanguajeLayout = new javax.swing.GroupLayout(PanelProgammingLanguaje);
        PanelProgammingLanguaje.setLayout(PanelProgammingLanguajeLayout);
        PanelProgammingLanguajeLayout.setHorizontalGroup(
            PanelProgammingLanguajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProgammingLanguajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProgrammingLanguaje)
                .addGap(18, 18, 18)
                .addComponent(rbtnPython, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnHtmlCss)
                .addGap(18, 18, 18)
                .addComponent(rbtnHtmlPhp)
                .addGap(18, 18, 18)
                .addComponent(rbtnHtmlJavaScript)
                .addGap(18, 18, 18)
                .addComponent(rbtnJava)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        PanelProgammingLanguajeLayout.setVerticalGroup(
            PanelProgammingLanguajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProgammingLanguajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelProgammingLanguajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgrammingLanguaje)
                    .addComponent(rbtnPython)
                    .addComponent(rbtnJava)
                    .addComponent(rbtnHtmlPhp)
                    .addComponent(rbtnHtmlJavaScript)
                    .addComponent(rbtnHtmlCss))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelServiceType.setPreferredSize(new java.awt.Dimension(0, 32));

        lblServiceType.setFont(new java.awt.Font("Town 10 Display Bold", 0, 12)); // NOI18N
        lblServiceType.setText("Tipo de ejercicio");

        btnGrServiceType.add(rbtnHomework);
        rbtnHomework.setText("Tarea");

        btnGrServiceType.add(rbtnTest);
        rbtnTest.setText("Prueba");

        javax.swing.GroupLayout PanelServiceTypeLayout = new javax.swing.GroupLayout(PanelServiceType);
        PanelServiceType.setLayout(PanelServiceTypeLayout);
        PanelServiceTypeLayout.setHorizontalGroup(
            PanelServiceTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelServiceTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblServiceType)
                .addGap(91, 91, 91)
                .addComponent(rbtnHomework, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnTest)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelServiceTypeLayout.setVerticalGroup(
            PanelServiceTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelServiceTypeLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(PanelServiceTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServiceType)
                    .addComponent(rbtnHomework)
                    .addComponent(rbtnTest))
                .addContainerGap())
        );

        PanelDeadline.setPreferredSize(new java.awt.Dimension(0, 36));

        lblDeadline.setFont(new java.awt.Font("Town 10 Display Bold", 0, 12)); // NOI18N
        lblDeadline.setText("Urgencia");

        spnDeadline.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spnDeadline.setEditor(new javax.swing.JSpinner.NumberEditor(spnDeadline, ""));
        spnDeadline.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnDeadlineStateChanged(evt);
            }
        });

        lblDays.setText("días de plazo");

        javax.swing.GroupLayout PanelDeadlineLayout = new javax.swing.GroupLayout(PanelDeadline);
        PanelDeadline.setLayout(PanelDeadlineLayout);
        PanelDeadlineLayout.setHorizontalGroup(
            PanelDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDeadlineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDeadline)
                .addGap(191, 191, 191)
                .addComponent(spnDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDays)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDeadlineLayout.setVerticalGroup(
            PanelDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDeadlineLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelDeadlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeadline)
                    .addComponent(spnDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDays))
                .addContainerGap())
        );

        lblExerciseNumber.setFont(new java.awt.Font("Town 10 Display Bold", 0, 12)); // NOI18N
        lblExerciseNumber.setText("Cantidad ejercicios");

        spnExercises.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spnExercises.setEditor(new javax.swing.JSpinner.NumberEditor(spnExercises, ""));
        spnExercises.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnExercisesStateChanged(evt);
            }
        });

        javax.swing.GroupLayout PanelExerciseNumberLayout = new javax.swing.GroupLayout(PanelExerciseNumber);
        PanelExerciseNumber.setLayout(PanelExerciseNumberLayout);
        PanelExerciseNumberLayout.setHorizontalGroup(
            PanelExerciseNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelExerciseNumberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExerciseNumber)
                .addGap(115, 115, 115)
                .addComponent(spnExercises, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelExerciseNumberLayout.setVerticalGroup(
            PanelExerciseNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelExerciseNumberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelExerciseNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnExercises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExerciseNumber))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExecuteCotization.setBackground(new java.awt.Color(182, 193, 255));
        btnExecuteCotization.setFont(new java.awt.Font("Town 10 Display Bold", 0, 14)); // NOI18N
        btnExecuteCotization.setText("COTIZAR");
        btnExecuteCotization.setAlignmentX(0.5F);
        btnExecuteCotization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteCotizationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCaseDataLayout = new javax.swing.GroupLayout(PanelCaseData);
        PanelCaseData.setLayout(PanelCaseDataLayout);
        PanelCaseDataLayout.setHorizontalGroup(
            PanelCaseDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCaseDataLayout.createSequentialGroup()
                .addGroup(PanelCaseDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PanelDeadline, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                    .addComponent(PanelExerciseNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelProgammingLanguaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelServiceType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelCaseDataLayout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(btnExecuteCotization)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCaseDataLayout.setVerticalGroup(
            PanelCaseDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCaseDataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelServiceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelProgammingLanguaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelExerciseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExecuteCotization)
                .addContainerGap())
        );

        SeparatorBottom.setPreferredSize(new java.awt.Dimension(50, 5));

        PanelCotization.setBackground(new java.awt.Color(0, 0, 0));

        lblCotizationPrice.setFont(new java.awt.Font("Town 10 Display Bold", 0, 18)); // NOI18N
        lblCotizationPrice.setForeground(new java.awt.Color(255, 204, 0));
        lblCotizationPrice.setText("El valor del ejercicio aparecerá aquí...");
        lblCotizationPrice.setAlignmentX(0.5F);

        btnAcceptCotization.setBackground(new java.awt.Color(255, 204, 51));
        btnAcceptCotization.setFont(new java.awt.Font("Town 10 Display Bold", 0, 14)); // NOI18N
        btnAcceptCotization.setText("aceptar");
        btnAcceptCotization.setMaximumSize(new java.awt.Dimension(86, 25));
        btnAcceptCotization.setMinimumSize(new java.awt.Dimension(86, 25));
        btnAcceptCotization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptCotizationActionPerformed(evt);
            }
        });

        lblCotizationNote.setFont(new java.awt.Font("Town 10 Display Bold", 0, 12)); // NOI18N
        lblCotizationNote.setForeground(new java.awt.Color(255, 204, 0));
        lblCotizationNote.setText("Nota: Debe pagarse la mitad por adelantado.");

        javax.swing.GroupLayout PanelCotizationLayout = new javax.swing.GroupLayout(PanelCotization);
        PanelCotization.setLayout(PanelCotizationLayout);
        PanelCotizationLayout.setHorizontalGroup(
            PanelCotizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCotizationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelCotizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCotizationNote)
                    .addComponent(lblCotizationPrice))
                .addGap(55, 55, 55)
                .addComponent(btnAcceptCotization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        PanelCotizationLayout.setVerticalGroup(
            PanelCotizationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCotizationLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblCotizationPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCotizationNote)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCotizationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAcceptCotization, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        PanelClientList.setBackground(new java.awt.Color(0, 0, 0));
        PanelClientList.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), java.awt.Color.black, java.awt.Color.black, java.awt.Color.black), "Clientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Town 10 Display Bold", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        cboxClientList.setModel(clientComboboxModel());
        cboxClientList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxClientListItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout PanelClientListLayout = new javax.swing.GroupLayout(PanelClientList);
        PanelClientList.setLayout(PanelClientListLayout);
        PanelClientListLayout.setHorizontalGroup(
            PanelClientListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboxClientList, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        PanelClientListLayout.setVerticalGroup(
            PanelClientListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboxClientList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelClientList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelCotization, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SeparatorBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelCaseData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelTittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelClientData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelTittle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelClientList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelClientData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelCaseData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeparatorBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelCotization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // NULL VALUES VERIFICATIONS
    private void txtClientNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClientNameFocusGained
        if("Nombre".equals(this.txtClientName.getText())){
            this.txtClientName.setText("");
        }
    }//GEN-LAST:event_txtClientNameFocusGained
    
    private void txtClientNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClientNameFocusLost
        String content = this.txtClientName.getText().replaceAll("\\s", "");
        if("".equals(content)){
            this.txtClientName.setText("Nombre");
        }
    }//GEN-LAST:event_txtClientNameFocusLost
    
    private void txtClientMailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClientMailFocusGained
        if("Correo electrónico".equals(this.txtClientMail.getText())){
            this.txtClientMail.setText("");
        }
    }//GEN-LAST:event_txtClientMailFocusGained
    
    private void txtClientMailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClientMailFocusLost
        String content = this.txtClientMail.getText().replaceAll("\\s", "");
        if("".equals(content)){
            this.txtClientMail.setText("Correo electrónico");
        }
    }//GEN-LAST:event_txtClientMailFocusLost
    
    private void txtClientTelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClientTelFocusGained
        if("Teléfono".equals(this.txtClientTel.getText())){
            this.txtClientTel.setText("");
        }
    }//GEN-LAST:event_txtClientTelFocusGained
    
    private void txtClientTelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClientTelFocusLost
        String content = this.txtClientTel.getText().replaceAll("\\s", "");
        if("".equals(content)){
            this.txtClientTel.setText("Teléfono");
        }
    }//GEN-LAST:event_txtClientTelFocusLost

    
    // CREATE NEW CLIENT IN DATABASE    
    private void btnSaveClientInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveClientInfoMouseClicked
        // OBTAIN FORM DATA
        String name = this.txtClientName.getText();
        String mail = this.txtClientMail.getText();
        String cellphone = this.txtClientTel.getText();
        String telcode = (String) this.cboxTelCodes.getSelectedItem();
        String full_number = telcode + cellphone;
        
        // CREATE NEW CLIENT
        Client new_client = new Client(name, full_number, mail);
        
        // ADD TO DATABASE
        if (!DB.insertClient(new_client)){
            JOptionPane.showMessageDialog(null, "Cliente ya existe en la base de datos.");
        }
                
        // RELOAD CLIENT LIST
        this.cboxClientList.setModel(clientComboboxModel());
        
        // CLEAR CLIENT DATA
        this.txtClientName.setFocusable(true);
        this.txtClientMail.setFocusable(true);
        this.txtClientTel.setFocusable(true);
    }//GEN-LAST:event_btnSaveClientInfoMouseClicked

    
    // FILL CLIENT INFO FROM DATABASE WHEN SELECTED
    private void cboxClientListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxClientListItemStateChanged
        // GET CLIENT MAIL
        String client_info = (String) this.cboxClientList.getSelectedItem();
        int separator_index = client_info.indexOf(" - ");
        String client_mail = client_info.substring(separator_index + 3);

        // FILL CLIENT INFO FROM DATABASE
        ResultSet client_data = (ResultSet) DB.searchClient(client_mail);
        try {
            // fech
            client_data.next();
            // fill data
            this.txtClientName.setText(client_data.getString("name"));
            this.txtClientTel.setText(client_data.getString("cellphone"));
            this.txtClientMail.setText(client_data.getString("email"));
            // fill client object
            case_client.setID(client_data.getInt("id"));
            case_client.setName(client_data.getString("name"));
            case_client.setCellphone(client_data.getString("cellphone"));
            case_client.setEmail(client_data.getString("email"));
            exercise_case.setClient(client_data.getInt("id"));
            // System.out.println(case_client.toString());
            // System.out.println(exercise_case.getClient());
        } 
        catch (SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cboxClientListItemStateChanged

    
    // FILL EXERCISE_CASE OBJECT INFO WHEN PARAMETERS CHANGE
    private void spnDeadlineStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnDeadlineStateChanged
        // TODO add your handling code here:
        exercise_case.setDays((int) this.spnDeadline.getValue());
        // System.out.println(exercise_case.toString());
    }//GEN-LAST:event_spnDeadlineStateChanged
    
    private void spnExercisesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnExercisesStateChanged
        // TODO add your handling code here:
        exercise_case.setExercise_number((int) this.spnExercises.getValue());
        // System.out.println(exercise_case.toString());
    }//GEN-LAST:event_spnExercisesStateChanged
        
    ActionListener radioListenerServices = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int selectedIndex = getSelectedRadioButtonIndexService();
                exercise_case.setType(selectedIndex+1);
                // System.out.println(exercise_case.toString());
            }
    };
        
    ActionListener radioListenerLanguages = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int selectedIndex = getSelectedRadioButtonIndexLanguage();
                exercise_case.setLanguage(selectedIndex+1);
                // System.out.println(exercise_case.toString());
            }
    };
    
    
    // PERFORM COTIZATION
    private void btnExecuteCotizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteCotizationActionPerformed
        
        // GET CASE FORM DATA
        int exercise_type = exercise_case.getType();
        int programming_language = exercise_case.getLanguage();
        int exercise_amount = exercise_case.getExercise_number();
        int deadline = exercise_case.getDays();
        
        // CALCULATE SCORE
        float score;
        int extension_range;
        
        if (exercise_amount <= 5){extension_range=1;}
        else if (exercise_amount <= 10){extension_range=2;}
        else if (exercise_amount <= 15){extension_range=3;}
        else if (exercise_amount <= 20){extension_range=4;}
        else {extension_range=5;}
        
        if (deadline <= 3) {score = exercise_type + programming_language + extension_range;}
        else if (deadline <= 6 ){score = (float) ((exercise_type + programming_language + extension_range) * 0.9);}
        else if (deadline <= 9 ){score = (float) ((exercise_type + programming_language + extension_range) * 0.8);}
        else if (deadline <= 12 ){score = (float) ((exercise_type + programming_language + extension_range) * 0.6);}
        else {score = (float) ((exercise_type + programming_language + extension_range) * 0.4);}
        
        // CALCULATE PRICE
        float price = getCotizationPrice(score);
        exercise_case.setPrice(price);
        showCotizationPrice(price);
//        System.out.println("Servicio: " + exercise_type +
//                "\nProgramming language: " + programming_language + 
//                "\nExtension range: " + extension_range +
//                "\nDeadline: " + deadline +
//                "\nScore: " + score + 
//                "\nPrice: " + price);
    }//GEN-LAST:event_btnExecuteCotizationActionPerformed

    private void btnAcceptCotizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptCotizationActionPerformed
        // System.out.println(exercise_case.toString());

        if (!DB.insertCase(exercise_case)){
            JOptionPane.showMessageDialog(null, "ERROR!! :,(");
        }
        else{
            JOptionPane.showMessageDialog(null, "Ejercicio agregado!");
        }
    }//GEN-LAST:event_btnAcceptCotizationActionPerformed

    private float getCotizationPrice(float score){
        float price = (score * 50000) / 12;
        price = Math.max(price, 5000);        
        return price;
    }    

    private void showCotizationPrice(float price){
        this.lblCotizationPrice.setText("El valor estimado es: " + String.valueOf((int) Math.round(price)) + " CLP.");
        this.lblCotizationNote.setText("Nota: Debe pagarse la mitad ("+String.valueOf((int) Math.round(price/2))+"  CLP) por adelantado.");
    }
    
    
    // FILL COMBOBOXES FROM DATABASE
    private ComboBoxModel clientComboboxModel(){
        ComboBoxModel<String> comboBoxModel = new ResultSetComboBoxModel(DB.listClients(), "name", "email");
        return comboBoxModel;
    }
       
    private ComboBoxModel telCodesComboBoxModel(){
        ComboBoxModel<String> comboBoxModel = new ResultSetComboBoxModel(DB.listTelcodes(), "code");
        return comboBoxModel;
    }

    
    // OBTAIN RADIOBUTTON INDEXES
    private int getSelectedRadioButtonIndexService() {
        Enumeration<AbstractButton> buttons = this.btnGrServiceType.getElements();
        int index = 0;
        while (buttons.hasMoreElements()) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return index;
            }
            index++;
        }
        // Return -1 if no radio button is selected
        return -1;
    }
        
    private int getSelectedRadioButtonIndexLanguage() {
        Enumeration<AbstractButton> buttons = this.btnGrLanguages.getElements();
        int index = 0;

        while (buttons.hasMoreElements()) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return index;
            }
            index++;
        }
        // Return -1 if no radio button is selected
        return -1;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCaseData;
    private javax.swing.JPanel PanelClientData;
    private javax.swing.JPanel PanelClientList;
    private javax.swing.JPanel PanelCotization;
    private javax.swing.JPanel PanelDeadline;
    private javax.swing.JPanel PanelExerciseNumber;
    private javax.swing.JPanel PanelProgammingLanguaje;
    private javax.swing.JPanel PanelServiceType;
    private javax.swing.JPanel PanelTittle;
    private javax.swing.JSeparator SeparatorBottom;
    private javax.swing.JButton btnAcceptCotization;
    private javax.swing.JButton btnExecuteCotization;
    private javax.swing.ButtonGroup btnGrLanguages;
    private javax.swing.ButtonGroup btnGrServiceType;
    private javax.swing.JButton btnSaveClientInfo;
    private javax.swing.JComboBox<String> cboxClientList;
    private javax.swing.JComboBox<String> cboxTelCodes;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel lblCotizationNote;
    private javax.swing.JLabel lblCotizationPrice;
    private javax.swing.JLabel lblDays;
    private javax.swing.JLabel lblDeadline;
    private javax.swing.JLabel lblExerciseNumber;
    private javax.swing.JLabel lblProgrammingLanguaje;
    private javax.swing.JLabel lblServiceType;
    private javax.swing.JLabel lnlTareProgramada;
    private javax.swing.JRadioButton rbtnHomework;
    private javax.swing.JRadioButton rbtnHtmlCss;
    private javax.swing.JRadioButton rbtnHtmlJavaScript;
    private javax.swing.JRadioButton rbtnHtmlPhp;
    private javax.swing.JRadioButton rbtnJava;
    private javax.swing.JRadioButton rbtnPython;
    private javax.swing.JRadioButton rbtnTest;
    private javax.swing.JSpinner spnDeadline;
    private javax.swing.JSpinner spnExercises;
    private javax.swing.JTextField txtClientMail;
    private javax.swing.JTextField txtClientName;
    private javax.swing.JTextField txtClientTel;
    // End of variables declaration//GEN-END:variables
}
